# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: Build
  jobs:
  - job: BuildImage
    displayName: Build
    pool: Default
    steps:
    - script: echo "Build and Push image"
- stage: Test
  dependsOn: Build
  jobs: 
  - deployment: deploy to test
    environment: smarthotel360-test.abc-fe88
    pool: default
    strategy:
      runOnce:
        deploy:
          steps:
           - script: echo kubectl get pods
             displayName: 'Getting pod details'
           - task: Kubernetes@1
             displayName: 'kubectl get'
             inputs:
              namespace: abc-fe88
              command: get
              arguments: pods
- stage: staging
  dependsOn: Test
  jobs:
    - deployment: deploy to staging
      environment: smarthotel360-staging.abc-fe88
      pool: prodpool
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo kubectl get pods
              displayName: 'Getting pod details'
            - task: Kubernetes@1
              displayName: 'kubectl get'
              inputs:
                namespace: 'abc-fe88'
                command: get
                arguments: pods